version: '3.7'

services:
  master:
    image: 'mysql:5.7'
    ports:
      - '3307:3306'
    volumes:
      - ./mysql-master.cnf:/etc/mysql/conf.d/mysql-master.cnf
    environment:
     - MYSQL_ROOT_PASSWORD=${MY_ROOT_PASSWORD}
     - MYSQL_USER=${MY_USER}
     - MYSQL_PASSWORD=${MY_PASSWORD}
     - MYSQL_DATABASE=${MY_DATABASE}

  slave:
    image: 'mysql:5.7'
    depends_on:
      - master
    ports:
      - '3308:3306'
    volumes:
      - ./mysql-slave-1.cnf:/etc/mysql/conf.d/mysql-slave-1.cnf
    environment:
     - MYSQL_ROOT_PASSWORD=${MY_ROOT_PASSWORD}
     - MYSQL_USER=${MY_USER}
     - MYSQL_PASSWORD=${MY_PASSWORD}
     - MYSQL_DATABASE=${MY_DATABASE}
